### ISSUE TITLE
String interpolation syntax {{}} cannot be used in map key hence atomic types not possible in map key.

### ISSUE THREAD

**Issue by lgfausak** [birchb1024/yamp#4]
Very interesting yaml template engine!  I have been playing around with it all weekend.

I have attempted a simple macro:
```
# vim: tabstop=8 expandtab shiftwidth=2 softtabstop=2
- defmacro:
    name: simple
    args: [ RU ]
    value:
      "{{RU}}":
        data : RU
---
testme:
  simple: { RU: 6 }

```

When I run this code I get:

```
testme:
  '6':
    data: 6

```

However, when I leave the type an int, I get a failure, e.g.:

```
# vim: tabstop=8 expandtab shiftwidth=2 softtabstop=2
- defmacro:
    name: simple
    args: [ RU ]
    value:
      RU:
        data : RU
---
testme:
  simple: { RU: 6 }

```
```
testme:
  RU:
    data: 6

```

If I attempt to use the curly braces to project the value, I get an error:

```
- defmacro:
    name: simple
    args: [ RU ]
    value:
      {{RU}}:
        data : RU
---
testme:
  simple: { RU: 6 }

```

```
Traceback (most recent call last):
  File "/usr/local/bin/yamp", line 726, in <module>
    expand_file(filename, new_globals(), expandafterload=True, outputfile=sys.stdout)
  File "/usr/local/bin/yamp", line 704, in expand_file
    result = file_types[suffix]()
  File "/usr/local/bin/yamp", line 647, in expand_yaml
    for tree in doc_gen:
  File "/usr/lib/python2.7/site-packages/yaml/__init__.py", line 130, in load_all
    yield loader.get_data()
  File "/usr/lib/python2.7/site-packages/yaml/constructor.py", line 39, in get_data
    return self.construct_document(self.get_node())
  File "/usr/lib/python2.7/site-packages/yaml/constructor.py", line 54, in construct_document
    for dummy in generator:
  File "/usr/lib/python2.7/site-packages/yaml/constructor.py", line 404, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/usr/lib/python2.7/site-packages/yaml/constructor.py", line 214, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/usr/lib/python2.7/site-packages/yaml/constructor.py", line 138, in construct_mapping
    "found unacceptable key (%s)" % exc, key_node.start_mark)
yaml.constructor.ConstructorError: while constructing a mapping
found unacceptable key (unhashable type: 'dict')
  in "/home/install/git/vcp2-inv/data/t.yaml", line 6, column 7

```

how can I make the output look like this:

```
testme:
  6:
    data: 6
```

**Comment by birchb1024** [comment]
This is a very interesting issue, thanks very much for raising it. The real problem here is that there is no way to force expansion of a non-string variable in a map key. I will rename the issue. 

Lets get the easy stuff out of the way.. The backtrace and 'unacceptable key' error actually comes from the YAML parser. So the following is invalid YAML!:

```- defmacro:
    name: simple
    args: [ RU ]
    value:
      {{RU}}:
        data : RU
```

You can check this here:  https://yaml-online-parser.appspot.com/. 

The real problem I have is how can we convey to the interpreter that it should expand a symbol without barfing in the parser. Right now I'm thinking of options. 

One is to have an implicit type conversion from a string expansion into atomic types so '{{RU}}' will be automatically converted to int. This has global implications.

Another option is to add a marker like dollar  - so you would say {$RU: data RU} (Some languages e.g. shell use a leading dollar sign in the symbol ($RU) to say 'this is a variable, evaluate'. I need to avoid using '$; in case it conflicts with some code Yamp is processing. I also need to avoid all other similar markers. )

Another option is an explicit type conversion macro like flatten. 

Happy to consider more options...

**Comment by lgfausak** [comment]
I think the proper syntax looks like this:

```
    name: simple
    args: [ RU ]
    value:
      RU:
        data : RU
```

Why does the RU need curlies around it when it is a key, but it doesn't need curlies when it is the value?  The RU is being properly replaced with the number, the key for the entire structure isn't.  The yaml parser handles the above snippet properly.  It is just the output looks like:

```
RU:
  data: 6
```
instead of
```
6:
  data: 6
```

It appears that the replace of RU with the number 6 is not occuring when the replacement happens in an unquoted top level key?

**Comment by birchb1024** [comment]
Yes I understand your question. The language treats the map keys like an lvalue in C or the variable name in Lisp setq. Essentially variable names are quoted by default (ie not expanded). This is deliberate. 

I am working on a patch which lets the caret (^) character signal that the map key is a variable name to be evaluated. (Like Lisp set). This seems to work fine - doesn't break the existing code unlike the other options I have tried.

Your code becomes:

```
- defmacro:
    name: simple
    args: [ RU ]
    value:
      ^RU:
        data : RU
```

**Comment by lgfausak** [comment]
I just tested the ^RU, works great! Looking through the commit I saw the comment about the curlies in the key, I guess I just missed that earlier.  I still think the logical syntax should not have a carrot, but I'll admit I don't know exactly how the code works... thank you, it is very nice to create a yaml text without using jinja.  I was really getting tired of the indent tracking.  This is perfect.
